package delphes;

public enum Intention {
	expiration_d_une_api,
	depot_de_demande_d_asile,
	ou_en_est_ma_demande_d_asile_en_cours,
	expiration_d_une_atda,
	mise_a_jour_infos_atda,
	demande_en_rapport_avec_procedure_dublin_en_cours,
	ressortissant_ukrainien_demande_un_nouveau_titre,
	ressortissant_ukrainien_demande_renouvellement_de_son_titre,
	ressortissant_ukrainien_autre_demande,
	demande_d_un_etudiant_en_programme_de_mobilite,
	demande_d_un_stagiaire_associe_en_profession_medicale,
	difficultes_avec_le_site_de_l_anef,
	changement_statut_etudiant_a_salarie,
	changement_statut_etudiant_a_recherche_d_emploi,
	sollicitation_titre_vie_privee_et_familiale_hors_anef,
	depot_d_une_demande_de_titre_et_je_n_arrive_pas_a_creer_mon_compte_anef,
	depot_d_une_demande_de_titre_et_autre_blocage_sur_le_site_de_l_anef,
	depot_d_une_demande_de_titre_et_autre_probleme_anef,
	je_veux_retourner_dans_mon_pays_pour_motif_exceptionnel,
	other

}
