llm_configs:

  - id: "tests"
    llm: "openai"
    model: "gpt-4o-mini"
    response_format_type: "pydantic_model"
    prompt_format: "markdown"
    temperature: 1

  - id: "openai1"
    llm: "openai"
    model: "gpt-4o-mini"
    response_format_type: "pydantic_model"
    prompt_format: "text"
    temperature: 1

  - id: "ollama1"
    llm: "ollama"
    model: "mistral-small"
    response_format_type: "json_object"
    prompt_format: "markdown"
    temperature: 1

  - id: "scaleway1"
    llm: "scaleway"
    model: "mistral-small-3.1-24b-instruct-2503"
    response_format_type: "json_object"
    prompt_format: "markdown"
    temperature: 1



